### ISSUE TITLE
Windows.Media.Ocr

### ISSUE THREAD

**Issue by Lakritzator** [mkoertgen/hello.ocr#1]
Sorry to contact you like this, buf I had a question about this repository.

Did you get your sample running with Windows.Media.Ocr instead of WindowsPreview.Media.Ocr?

I am having problems creating a SoftwareBitmap from a GDI Image or WPF BitmapImage. I tried to create it via going through Windows.UI.Xaml.Media.Imaging.WriteableBitmap but whenever I call the constructor I get "The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))"

Maybe you have found a different way, or are not getting a problem?

**Comment by Lakritzator** [comment]
Actually I got it working via a decoder...

As the RecognizeAsync now wants a SoftwareBitmap, your example didn't work anymore

Anyway, you can get a SoftwareBitmap a follows:
``
 var decoder = await BitmapDecoder.CreateAsync(stream);
 var softwareBitmap = await decoder.GetSoftwareBitmapAsync();
``

**Comment by mkoertgen** [comment]
Yes, i noticed the Api changed in win10 since preview - for the better ;-)
